#!/bin/sh

#void linux setup script 
set -e

SCRIPT_URL="https://gitlab.com/shrek68/dotfiles/-/raw/master/scripts/setupScript/setupScript.sh"

sudo -v 
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "[+] Bootstrapping system..."
sudo xbps-install -y wget curl

echo "[+] Downloading main setup script..."
wget -q "$SCRIPT_URL" -O setupScript.sh

echo "[+] Launching setup..."
chmod +x setupScript.sh
yes | ./setupScript.sh
